-- Qual produto gerou mais receita total?
SELECT
	P.NOME,
	SUM(P.PRECO * I.QUANTIDADE) VALOR_TOTAL
FROM
	PRODUTOS P
	JOIN ITENSPEDIDO I
		ON I.PRODUTOID = P.PRODUTOID
GROUP BY
	P.NOME
ORDER BY
	SUM(P.PRECO * I.QUANTIDADE) DESC
LIMIT 1;

-- Quantos clientes compraram em setembro de 2025?
SELECT
	COUNT(DISTINCT C.NOME) QUANTIDADE_CLIENTES
FROM
	CLIENTES C
	JOIN PEDIDOS P
		ON P.CLIENTEID = C.CLIENTEID
WHERE
	P.DATAPEDIDO BETWEEN '2025-09-01' AND '2025-09-30';


-- Qual a diferença entre o maior e menor ticket de pedido?
SELECT
	MAX(PED.VALOR_TOTAL) - MIN(PED.VALOR_TOTAL) AS DIFERENCA_TICKETS
FROM
	(
		SELECT
			P.PEDIDOID,
			(SUM(I.QUANTIDADE * P2.PRECO)) AS VALOR_TOTAL
		FROM
			PEDIDOS P
			JOIN ITENSPEDIDO I ON I.PEDIDOID = P.PEDIDOID
			JOIN PRODUTOS P2 ON P2.PRODUTOID = I.PRODUTOID
		GROUP BY
			P.PEDIDOID
	) AS PED;
