-- 7. Liste os clientes que já compraram mais de um tipo diferente de produto
SELECT
	C.NOME
FROM
	CLIENTES C
	JOIN PEDIDOS P
		ON P.CLIENTEID = C.CLIENTEID
	JOIN ITENSPEDIDO I
		ON I.PEDIDOID = P.PEDIDOID
GROUP BY
	C.NOME
HAVING
	COUNT(DISTINCT I.PRODUTOID) > 1;

-- 8. Mostre os pedidos cujo valor total foi acima de R$ 3000
SELECT
	P.PEDIDOID,
	TO_CHAR(P.DATAPEDIDO, 'DD/MM/YYYY') DATA,
	SUM(I.QUANTIDADE * P2.PRECO) VALOR_TOTAL
FROM
	PEDIDOS P
	JOIN ITENSPEDIDO I
		ON I.PEDIDOID = P.PEDIDOID
	JOIN PRODUTOS P2
		ON P2.PRODUTOID = I.PRODUTOID
GROUP BY
	P.PEDIDOID,
	P.DATAPEDIDO
HAVING
	SUM(I.QUANTIDADE * P2.PRECO) > 3000;

-- 9. Calcule o ticket médio dos clientes (média de valor gasto por pedido)
SELECT
	C.NOME,
	AVG(PED.VALOR_TOTAL)::NUMERIC(10,2) TICKET_MEDIO
FROM
	CLIENTES C
	JOIN (
		SELECT
			P.PEDIDOID,
			P.CLIENTEID,
			SUM(COALESCE(P2.PRECO * I.QUANTIDADE, 0)) AS VALOR_TOTAL
		FROM
			PEDIDOS P
		LEFT JOIN ITENSPEDIDO I
			ON I.PEDIDOID = P.PEDIDOID
		LEFT JOIN PRODUTOS P2
			ON P2.PRODUTOID = I.PRODUTOID
		GROUP BY
			P.PEDIDOID,
			P.CLIENTEID
	) AS PED
		ON PED.CLIENTEID = C.CLIENTEID
GROUP BY
	C.NOME
ORDER BY
	C.NOME;

-- 10. Liste os clientes que nunca fizeram pedidos
SELECT
	C.NOME
FROM
	CLIENTES C
	LEFT JOIN PEDIDOS P
		ON P.CLIENTEID = C.CLIENTEID
WHERE
	P.PEDIDOID IS NULL;
