-- 4. Exiba o valor total de cada pedido
SELECT
	P.PEDIDOID,
	TO_CHAR(P.DATAPEDIDO, 'DD/MM/YYYY') DATA_PEDIDO,
	SUM(I.QUANTIDADE * P2.PRECO) VALOR_TOTAL
FROM
	PEDIDOS P
	JOIN ITENSPEDIDO I
		ON I.PEDIDOID = P.PEDIDOID
	JOIN PRODUTOS P2
		ON P2.PRODUTOID = I.PRODUTOID
GROUP BY
	P.PEDIDOID,
	P.DATAPEDIDO
ORDER BY
	P.PEDIDOID;

-- 5. Traga o total gasto por cada cliente
SELECT
	C.NOME,
	SUM(P2.PRECO * I.QUANTIDADE) AS VALOR_TOTAL
FROM
	CLIENTES C
	JOIN PEDIDOS P
		ON P.CLIENTEID = C.CLIENTEID
	JOIN ITENSPEDIDO I
		ON I.PEDIDOID = P.PEDIDOID
	JOIN PRODUTOS P2
		ON P2.PRODUTOID = I.PRODUTOID
GROUP BY
	C.NOME;

-- 6. Mostre os produtos mais vendidos em quantidade
SELECT
	P.NOME,
	SUM(I.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
	PRODUTOS P
	JOIN ITENSPEDIDO I
		ON P.PRODUTOID = I.PRODUTOID
GROUP BY
	P.NOME,
	P.CATEGORIA
ORDER BY
	SUM(I.QUANTIDADE) DESC
